//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WalletWPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Commitment
    {
        public int id_commitment { get; set; }
        public string name { get; set; }
        public Nullable<double> amount { get; set; }
        public Nullable<int> number_of_installments { get; set; }
        public Nullable<System.DateTime> date { get; set; }
    }
}
