//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WalletWPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConstOrder
    {
        public int id_const_order { get; set; }
        public string name { get; set; }
        public Nullable<double> amount { get; set; }
        public Nullable<System.DateTime> date_const_order { get; set; }
        public Nullable<int> id_subcategory { get; set; }
    
        public virtual Subcategory Subcategory { get; set; }
    }
}
