//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WalletWPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int Id_transaction { get; set; }
        public string name { get; set; }
        public string category { get; set; }
        public string subcategory { get; set; }
        public string paymentMethod { get; set; }
        public Nullable<double> amount { get; set; }
        public Nullable<System.DateTime> date_transaction { get; set; }
        public Nullable<int> id_payment_method { get; set; }
        public Nullable<int> id_subcategory { get; set; }
    
        public virtual PaymentMethod PaymentMethod { get; set; }
        public virtual Subcategory Subcategory { get; set; }
    }
}
